### ISSUE TITLE
Tapping on UINavigationController disables swiping

### ISSUE THREAD

**Issue by ghost** [hyperoslo/Presentation#86] opened 2017-01-17 23:24 UTC
In both samples, tapping on the `UINavigationController`'s next or previous buttons  disables the swiping of the pages.

The swiping should still be allowed when the user uses one of these nav buttons.

**Comment by PaulAbrudan** [comment] 2017-03-14 23:32
It took me a while to realize that there is an animation timer set up that disables the interaction of the underlying UIScrollView of UIPageViewController until it runs out. I'm not exactly sure why that timer is there in the first place, I'm sure there must be a reason (I'll look into it this weekend). Anyway, so to fix it what I did was reduce the timer from 3 seconds to 0.1 in a subclass I had initially made for other reasons.

**Comment by vadymmarkov** [comment] 2017-03-22 23:13
@PaulAbrudan  
Swiping will be disabled only for 3 seconds after you tap on the `UINavigationController`'s next or previous buttons. This time interval is controlled by `maxAnimationDelay` property of `PresentationController` which was introduced to wait until all the animations complete https://github.com/hyperoslo/Presentation/pull/72. It's an `open` var, so you can set it to 0.1, for example, if it doesn't break anything in your app.

**Comment by vadymmarkov** [comment] 2017-03-22 23:14
I think we can close this now.

**Comment by PaulAbrudan** [comment] 2017-03-22 23:15
Thanks @vadymmarkov for confirming! I figured it out and posted the response so that if other users are having the same issue they know how to quickly fix it.

Thanks for the awesome library!

**Closed by vadymmarkov** 2017-03-22 23:14 UTC

**Comment by PaulAbrudan** [comment] 2017-03-22 23:16
It's not a bug. It's a feature. #DevLife

**Comment by vadymmarkov** [comment] 2017-03-22 23:18
@PaulAbrudan You're welcome 👍
