### ISSUE TITLE
Gestures are not working

### ISSUE THREAD

**Issue by tosbaha** [hyperoslo/Presentation#103] opened 2018-03-03 13:26 UTC
If I use gestures and swipe left,right text changes but parallax effect doesn't work. However if I use Previous and Next page button animations work as it intended. 
![anim](https://user-images.githubusercontent.com/971530/36934785-8f354250-1eff-11e8-863f-0e5f0f7336c5.gif)

**Comment by vadymmarkov** [comment] 2018-03-03 16:25
Thanks for reporting this @tosbaha. The issue is fixed now https://github.com/hyperoslo/Presentation/pull/104

**Closed by vadymmarkov** 2018-03-03 16:25 UTC
